
import java.awt.Toolkit;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author robwo
 */
public class frm_PlayerRegistration extends javax.swing.JFrame {
    
    /**
     * Creates new form Player_Info
     */
    public frm_PlayerRegistration() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        reg_Picture = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        pnl_PlayerInfo = new javax.swing.JPanel();
        lbl_FirstName = new javax.swing.JLabel();
        lbl_LastName = new javax.swing.JLabel();
        txt_FirstName = new javax.swing.JTextField();
        txt_LastName = new javax.swing.JTextField();
        btn_AddPlayer = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        lbl_Registration_Username = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        lbl_Registration_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txt_confirmPassword = new javax.swing.JPasswordField();
        menu_Main = new javax.swing.JMenuBar();
        menu_main_File = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_Exit = new javax.swing.JMenuItem();
        menu_main_Help = new javax.swing.JMenu();
        menu_About = new javax.swing.JMenuItem();
        menu_Help_Howto = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Player Registration");
        setBackground(new java.awt.Color(0, 41, 60));

        jPanel1.setBackground(new java.awt.Color(0, 41, 60));

        pnl_PlayerInfo.setBackground(new java.awt.Color(0, 41, 60));
        pnl_PlayerInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0), 2));

        lbl_FirstName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_FirstName.setForeground(new java.awt.Color(241, 243, 206));
        lbl_FirstName.setText("First Name");

        lbl_LastName.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_LastName.setForeground(new java.awt.Color(241, 243, 206));
        lbl_LastName.setText("Last Name");

        txt_FirstName.setBackground(new java.awt.Color(241, 243, 206));
        txt_FirstName.setForeground(new java.awt.Color(0, 41, 60));
        txt_FirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));
        txt_FirstName.setPreferredSize(new java.awt.Dimension(6, 20));

        txt_LastName.setBackground(new java.awt.Color(241, 243, 206));
        txt_LastName.setForeground(new java.awt.Color(0, 41, 60));
        txt_LastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));
        txt_LastName.setPreferredSize(new java.awt.Dimension(6, 20));

        btn_AddPlayer.setBackground(new java.awt.Color(246, 42, 0));
        btn_AddPlayer.setForeground(new java.awt.Color(241, 243, 206));
        btn_AddPlayer.setText("Add Player");
        btn_AddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddPlayerActionPerformed(evt);
            }
        });

        btn_Clear.setBackground(new java.awt.Color(246, 42, 0));
        btn_Clear.setForeground(new java.awt.Color(241, 243, 206));
        btn_Clear.setText("Clear Form");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Exit.setBackground(new java.awt.Color(246, 42, 0));
        btn_Exit.setForeground(new java.awt.Color(241, 243, 206));
        btn_Exit.setText("Cancel");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        lbl_Registration_Username.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_Registration_Username.setForeground(new java.awt.Color(241, 243, 206));
        lbl_Registration_Username.setText("Username");
        lbl_Registration_Username.setPreferredSize(new java.awt.Dimension(64, 17));

        txt_Username.setBackground(new java.awt.Color(241, 243, 206));
        txt_Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));
        txt_Username.setPreferredSize(new java.awt.Dimension(6, 20));

        lbl_Registration_Password.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_Registration_Password.setForeground(new java.awt.Color(241, 243, 206));
        lbl_Registration_Password.setText("Password");

        txt_Password.setBackground(new java.awt.Color(241, 243, 206));
        txt_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));
        txt_Password.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 243, 206));
        jLabel1.setText("Confirm Password");

        txt_confirmPassword.setBackground(new java.awt.Color(241, 243, 206));
        txt_confirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));
        txt_confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_PlayerInfoLayout = new javax.swing.GroupLayout(pnl_PlayerInfo);
        pnl_PlayerInfo.setLayout(pnl_PlayerInfoLayout);
        pnl_PlayerInfoLayout.setHorizontalGroup(
            pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PlayerInfoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_AddPlayer)
                .addGap(39, 39, 39)
                .addComponent(btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(pnl_PlayerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_Registration_Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Registration_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_PlayerInfoLayout.setVerticalGroup(
            pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PlayerInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PlayerInfoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Registration_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(txt_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PlayerInfoLayout.createSequentialGroup()
                        .addComponent(lbl_Registration_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)))
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_PlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(pnl_PlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(pnl_PlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        menu_main_File.setText("File");
        menu_main_File.setToolTipText("File");
        menu_main_File.add(jSeparator1);

        menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/powerlittle.png"))); // NOI18N
        menu_Exit.setText("Exit");
        menu_Exit.setToolTipText("Exit System");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        menu_main_File.add(menu_Exit);

        menu_Main.add(menu_main_File);

        menu_main_Help.setText("Help");

        menu_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menu_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radarlogoIcon.png"))); // NOI18N
        menu_About.setText("About");
        menu_About.setToolTipText("About");
        menu_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AboutActionPerformed(evt);
            }
        });
        menu_main_Help.add(menu_About);

        menu_Help_Howto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/messages2small.png"))); // NOI18N
        menu_Help_Howto.setText("Help");
        menu_Help_Howto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Help_HowtoActionPerformed(evt);
            }
        });
        menu_main_Help.add(menu_Help_Howto);

        menu_Main.add(menu_main_Help);

        setJMenuBar(menu_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method cancels the player registration and returns to the login page
     * when the Cancel button is clicked.
     * @param evt 
     */
    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        new frm_LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * This method clears the form when the Clear button is clicked.
     * @param evt 
     */
    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_FirstName.setText("");
        txt_LastName.setText("");
        txt_Username.setText("");
        txt_Password.setText("");
        txt_confirmPassword.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    /**
     * This method exits the program when Exit Menu Item is clicked.
     * @param evt 
     */
    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_ExitActionPerformed

    /**
     * This method creates and displays the About Form when the About Menu Item 
     * is clicked.
     * @param evt 
     */
    private void menu_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AboutActionPerformed
        new frm_About().setVisible(true);
    }//GEN-LAST:event_menu_AboutActionPerformed

    /**
     * This method creates a user account and adds the user's information to the 
     * database when the Add Player button is clicked.
     * The database must not contain the username entered for the user to create
     * a new account.
     * @param evt 
     */
    private void btn_AddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddPlayerActionPerformed
        // Declare variables and set them equal to the text from the textboxes
        String firstName = txt_FirstName.getText();
        String lastName = txt_LastName.getText();
        String username = txt_Username.getText();
        char[] passwordArray = txt_Password.getPassword();
        String password = "";
        char[] confirmArray = txt_confirmPassword.getPassword();
        String confirmPassword = "";
        
        // Add each character in the passwordArray to the password string
        for (int i = 0; i < passwordArray.length; i++) {
            password += passwordArray[i];
        }
        
        // Add each character in the confirmArray to the confirmPassword string
        for(int i = 0; i < confirmArray.length; i++){
            confirmPassword += confirmArray[i];
        }

        // Connect to database and verify new user creation
        try {
            // Connect to the database
            DBConnect con = new DBConnect();
            // Select values from database
            ResultSet rs = con.getStatement().executeQuery("SELECT * FROM " +
                    "LoginInfo");

            int id = 1; // id for new player
            ArrayList<String> array = new ArrayList<>();
            /* Set the id to 1 greater than the last user id in the database
                and add each username from the database to the array */
            while (rs.next()) {
                id = Integer.parseInt(rs.getString(1)) + 1;
                array.add(rs.getString(2));
            }
            
            int a = 0;
            int b = 0;
            int c = 0;
            // Password must be at least 6 characters long
            boolean length = (password.length() >= 6);
            
            /* Insert player info if database doesn't contain username and 
                required fields are not empty */
            if((!username.equals("") && !password.equals("") && length && 
                    !firstName.equals("") && !lastName.equals("")) && 
                    !array.contains(username) && (confirmPassword.equals(password))){
                // Insert textbox values into the LoginInfo table
                a = con.getStatement().executeUpdate("INSERT INTO LoginInfo (PlayerId, "
                        + "Username, Password) VALUES ('" + id
                        + "', '" + username + "', '" + password + "')");
                // Insert textbox values into the PlayerInfo table
                b = con.getStatement().executeUpdate("INSERT INTO PlayerInfo (PlayerId, "
                        + "FirstName, LastName) VALUES ('" + id + "', '" + firstName
                        + "', '" + lastName + "')");
                // Insert playerId into BowlerAverages table
                c = con.getStatement().executeUpdate("INSERT INTO BowlerAverages " +
                        "(PlayerId) VALUES ('" + id + "')");
            }

            /* Validate if the INSERT statements were successful, if the
                username and password contain a string, and if the array does
                not contain the username that is being created */
            if(a == 1 && b == 1 && c == 1){
                // Successful creation of a user account
                JOptionPane.showMessageDialog(null, "Successful");
                txt_Password.setText("");
                
                // Create and display LoginPage Form
                new frm_LoginPage().setVisible(true);
                
                // Close database connection and dispose of this form
                con.getConnection().close();
                this.dispose();
            }else{ // If INSERT statements, the username, and the password fail
                JOptionPane.showMessageDialog(null, "Failed");
                txt_Password.setText("");
            }
        }catch(Exception e){ // Print error if there is a problem with database
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_btn_AddPlayerActionPerformed

    private void txt_confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmPasswordActionPerformed

    private void menu_Help_HowtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Help_HowtoActionPerformed
        // TODO add your handling code here:
        try{
            //            String URL = "Howto/GameTrakker_HowTo.html";
            //            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

            Desktop.getDesktop().open(new File("Howto\\GameTrakker_HowTo.html"));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_menu_Help_HowtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_PlayerRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddPlayer;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_FirstName;
    private javax.swing.JLabel lbl_LastName;
    private javax.swing.JLabel lbl_Registration_Password;
    private javax.swing.JLabel lbl_Registration_Username;
    private javax.swing.JMenuItem menu_About;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JMenuItem menu_Help_Howto;
    private javax.swing.JMenuBar menu_Main;
    private javax.swing.JMenu menu_main_File;
    private javax.swing.JMenu menu_main_Help;
    private javax.swing.JPanel pnl_PlayerInfo;
    private javax.swing.JFileChooser reg_Picture;
    private javax.swing.JTextField txt_FirstName;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    private javax.swing.JPasswordField txt_confirmPassword;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("radarlogoIcon.png")));
    }
}
