
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rob
 */
public class frm_Tournament extends javax.swing.JFrame {

    ArrayList<String> bowlers = new ArrayList();

    /**
     * Creates new form frm_Tournament
     */
    public frm_Tournament() {
        initComponents();
        txt_Tournaments_player1Score.setText("");
        txt_Tournaments_player2Score.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lbl_Tournaments_bracket2_player7 = new javax.swing.JLabel();
        lbl_Tournaments_bracket2_player8 = new javax.swing.JLabel();
        lbl_Tournaments_bracket3_player3 = new javax.swing.JLabel();
        lbl_Tournaments_bracket3_player4 = new javax.swing.JLabel();
        txt_Tounament_player9 = new javax.swing.JTextField();
        txt_Tounament_player10 = new javax.swing.JTextField();
        txt_Tounament_player11 = new javax.swing.JTextField();
        txt_Tounament_player12 = new javax.swing.JTextField();
        txt_Tounament_player13 = new javax.swing.JTextField();
        txt_Tounament_player14 = new javax.swing.JTextField();
        txt_Tounament_player15 = new javax.swing.JTextField();
        txt_Tournaments_player1Score1 = new javax.swing.JTextField();
        txt_Tournaments_player2Score1 = new javax.swing.JTextField();
        txt_Tournaments_player3Score1 = new javax.swing.JTextField();
        txt_Tournaments_player4Score1 = new javax.swing.JTextField();
        txt_Tournaments_player5Score1 = new javax.swing.JTextField();
        txt_Tournaments_player6Score1 = new javax.swing.JTextField();
        txt_Tournaments_player7Score1 = new javax.swing.JTextField();
        txt_Tournaments_player8Score1 = new javax.swing.JTextField();
        txt_Tounament_player16 = new javax.swing.JTextField();
        lbl_Tournaments_bracket4_player2 = new javax.swing.JLabel();
        txt_Tournaments_bracket2_score5 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score6 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score7 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score8 = new javax.swing.JTextField();
        txt_Tournaments_bracket4_score2 = new javax.swing.JTextField();
        txt_Tournaments_bracket3_score3 = new javax.swing.JTextField();
        txt_Tournaments_bracket3_score4 = new javax.swing.JTextField();
        lbl_Tournaments_bracket2_player5 = new javax.swing.JLabel();
        lbl_Tournaments_bracket2_player6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_Tounament_player6 = new javax.swing.JTextField();
        txt_Tounament_player5 = new javax.swing.JTextField();
        txt_Tounament_player4 = new javax.swing.JTextField();
        txt_Tounament_player3 = new javax.swing.JTextField();
        lbl_Tournaments_bracket4_player1 = new javax.swing.JLabel();
        txt_Tounament_player2 = new javax.swing.JTextField();
        txt_Tounament_player8 = new javax.swing.JTextField();
        txt_Tournaments_player2Score = new javax.swing.JTextField();
        txt_Tournaments_player3Score = new javax.swing.JTextField();
        txt_Tournaments_player4Score = new javax.swing.JTextField();
        txt_Tournaments_player5Score = new javax.swing.JTextField();
        txt_Tournaments_player6Score = new javax.swing.JTextField();
        txt_Tournaments_player7Score = new javax.swing.JTextField();
        txt_Tournaments_player8Score = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score1 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score2 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score3 = new javax.swing.JTextField();
        txt_Tournaments_bracket2_score4 = new javax.swing.JTextField();
        txt_Tournaments_bracket4_score1 = new javax.swing.JTextField();
        txt_Tournaments_bracket3_score1 = new javax.swing.JTextField();
        txt_Tournaments_bracket3_score2 = new javax.swing.JTextField();
        lbl_Tournaments_bracket2_player1 = new javax.swing.JLabel();
        lbl_Tournaments_bracket2_player3 = new javax.swing.JLabel();
        lbl_Tournaments_bracket2_player2 = new javax.swing.JLabel();
        txt_Tounament_player7 = new javax.swing.JTextField();
        lbl_Tournaments_bracket2_player4 = new javax.swing.JLabel();
        lbl_Tournaments_bracket3_player2 = new javax.swing.JLabel();
        lbl_Tournaments_bracket3_player1 = new javax.swing.JLabel();
        txt_Tournaments_player1Score = new javax.swing.JTextField();
        txt_Tounament_player1 = new javax.swing.JTextField();
        btn_Var = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_Tournaments_bracket2_player7.setText("Player");

        lbl_Tournaments_bracket2_player8.setText("Player");

        lbl_Tournaments_bracket3_player3.setText("Player");

        lbl_Tournaments_bracket3_player4.setText("Player");

        txt_Tournaments_player3Score1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Tournaments_player3Score1ActionPerformed(evt);
            }
        });

        lbl_Tournaments_bracket4_player2.setText("Player");

        lbl_Tournaments_bracket2_player5.setText("Player");

        lbl_Tournaments_bracket2_player6.setText("Player");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_Tournaments_bracket3_player4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Tournaments_bracket3_score3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_Tournaments_bracket3_player3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Tournaments_bracket3_score4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_Tournaments_bracket2_score6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Tournaments_bracket2_player7)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_Tournaments_bracket2_score7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Tournaments_bracket2_player6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_Tournaments_bracket2_score8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Tournaments_bracket2_player8))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_Tournaments_bracket2_score5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Tournaments_bracket2_player5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbl_Tournaments_bracket4_player2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tournaments_bracket4_score2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Tournaments_player4Score1)
                    .addComponent(txt_Tournaments_player2Score1)
                    .addComponent(txt_Tournaments_player3Score1)
                    .addComponent(txt_Tournaments_player5Score1)
                    .addComponent(txt_Tournaments_player6Score1)
                    .addComponent(txt_Tournaments_player7Score1)
                    .addComponent(txt_Tournaments_player8Score1)
                    .addComponent(txt_Tournaments_player1Score1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Tounament_player16)
                    .addComponent(txt_Tounament_player11)
                    .addComponent(txt_Tounament_player12)
                    .addComponent(txt_Tounament_player13)
                    .addComponent(txt_Tounament_player15)
                    .addComponent(txt_Tounament_player9)
                    .addComponent(txt_Tounament_player10)
                    .addComponent(txt_Tounament_player14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_Tournaments_player3Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tournaments_player4Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(txt_Tournaments_player5Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Tournaments_player6Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txt_Tournaments_player7Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Tournaments_player8Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tournaments_bracket3_player4)
                    .addComponent(txt_Tournaments_bracket3_score3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Tournaments_bracket4_score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Tournaments_bracket4_player2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tournaments_bracket3_player3)
                    .addComponent(txt_Tournaments_bracket3_score4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_Tournaments_player1Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Tournaments_player2Score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_Tounament_player14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Tounament_player13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(txt_Tounament_player10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_Tounament_player12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Tounament_player11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Tounament_player9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txt_Tounament_player16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Tounament_player15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tournaments_bracket2_score5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tournaments_bracket2_player5))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket2_player7)
                            .addComponent(txt_Tournaments_bracket2_score6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tournaments_bracket2_score7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tournaments_bracket2_player6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tournaments_bracket2_score8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Tournaments_bracket2_player8))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbl_Tournaments_bracket4_player1.setText("Player");

        txt_Tournaments_player3Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Tournaments_player3ScoreActionPerformed(evt);
            }
        });

        lbl_Tournaments_bracket2_player1.setText("Player");

        lbl_Tournaments_bracket2_player3.setText("Player");

        lbl_Tournaments_bracket2_player2.setText("Player");

        lbl_Tournaments_bracket2_player4.setText("Player");

        lbl_Tournaments_bracket3_player2.setText("Player");

        lbl_Tournaments_bracket3_player1.setText("Player");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Tounament_player7)
                            .addComponent(txt_Tounament_player4)
                            .addComponent(txt_Tounament_player3)
                            .addComponent(txt_Tounament_player2)
                            .addComponent(txt_Tounament_player8)
                            .addComponent(txt_Tounament_player6)
                            .addComponent(txt_Tounament_player5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Tournaments_player4Score)
                            .addComponent(txt_Tournaments_player2Score)
                            .addComponent(txt_Tournaments_player3Score)
                            .addComponent(txt_Tournaments_player5Score)
                            .addComponent(txt_Tournaments_player6Score)
                            .addComponent(txt_Tournaments_player7Score)
                            .addComponent(txt_Tournaments_player8Score, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_Tounament_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Tournaments_player1Score, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_Tournaments_bracket2_player1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tournaments_bracket2_score1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_Tournaments_bracket2_player2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tournaments_bracket2_score2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_Tournaments_bracket2_player4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Tournaments_bracket2_score4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(185, 185, 185))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_Tournaments_bracket3_player2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tournaments_bracket3_score2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbl_Tournaments_bracket3_player1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tournaments_bracket3_score1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_Tournaments_bracket2_player3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Tournaments_bracket2_score3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Tournaments_bracket4_player1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tournaments_bracket4_score1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tournaments_bracket2_player1)
                    .addComponent(txt_Tournaments_bracket2_score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket2_player2)
                            .addComponent(txt_Tournaments_bracket2_score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket2_player3)
                            .addComponent(txt_Tournaments_bracket2_score3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket2_player4)
                            .addComponent(txt_Tournaments_bracket2_score4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket3_player1)
                            .addComponent(txt_Tournaments_bracket3_score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket4_player1)
                            .addComponent(txt_Tournaments_bracket4_score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Tournaments_bracket3_player2)
                            .addComponent(txt_Tournaments_bracket3_score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Tounament_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tournaments_player1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tounament_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tournaments_player2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tounament_player5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tournaments_player5Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tounament_player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tournaments_player3Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Tounament_player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Tournaments_player4Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tounament_player6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tournaments_player6Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tounament_player7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tournaments_player7Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tounament_player8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tournaments_player8Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Var.setText("2nd Bracket");
        btn_Var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VarActionPerformed(evt);
            }
        });

        jButton2.setText("3rd Bracket");

        jButton3.setText("Final Game");

        jButton1.setText("1st Bracket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Var)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(7, 7, 7)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(btn_Var)
                        .addGap(179, 179, 179))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Tournaments_player3Score1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Tournaments_player3Score1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Tournaments_player3Score1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_VarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VarActionPerformed
        // TODO add your handling code here:
        //bowlers.add(txt_Test.getText());
        
        System.out.println(bowlers);
        //        for (int i = 0 ; i< bowlers.size() ; i++){
            //            txt_Name1.setText(bowlers.get(i));
            //            //txt_Name2.setText(bowlers.get(i));
            //        }
        for (String str : bowlers) {
            int i;
            //            txt_Tournaments_player1Score.setText(bowlers.get());
            //            txt_Tournaments_player2Score.setText(bowlers.get(str));

        }
        //        TestVar.setText(bowlers);

        //        for (String str : bowlers) {
            //            TestVar.append(str + "\n");
            //        }
        //t/xt_Test.requestFocus();

    }//GEN-LAST:event_btn_VarActionPerformed

    private void txt_Tournaments_player3ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Tournaments_player3ScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Tournaments_player3ScoreActionPerformed

    //* @param args the command line arguments
    //*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Tournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Tournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Tournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Tournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Tournament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Var;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player1;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player2;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player3;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player4;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player5;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player6;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player7;
    private javax.swing.JLabel lbl_Tournaments_bracket2_player8;
    private javax.swing.JLabel lbl_Tournaments_bracket3_player1;
    private javax.swing.JLabel lbl_Tournaments_bracket3_player2;
    private javax.swing.JLabel lbl_Tournaments_bracket3_player3;
    private javax.swing.JLabel lbl_Tournaments_bracket3_player4;
    private javax.swing.JLabel lbl_Tournaments_bracket4_player1;
    private javax.swing.JLabel lbl_Tournaments_bracket4_player2;
    private javax.swing.JTextField txt_Tounament_player1;
    private javax.swing.JTextField txt_Tounament_player10;
    private javax.swing.JTextField txt_Tounament_player11;
    private javax.swing.JTextField txt_Tounament_player12;
    private javax.swing.JTextField txt_Tounament_player13;
    private javax.swing.JTextField txt_Tounament_player14;
    private javax.swing.JTextField txt_Tounament_player15;
    private javax.swing.JTextField txt_Tounament_player16;
    private javax.swing.JTextField txt_Tounament_player2;
    private javax.swing.JTextField txt_Tounament_player3;
    private javax.swing.JTextField txt_Tounament_player4;
    private javax.swing.JTextField txt_Tounament_player5;
    private javax.swing.JTextField txt_Tounament_player6;
    private javax.swing.JTextField txt_Tounament_player7;
    private javax.swing.JTextField txt_Tounament_player8;
    private javax.swing.JTextField txt_Tounament_player9;
    private javax.swing.JTextField txt_Tournaments_bracket2_score1;
    private javax.swing.JTextField txt_Tournaments_bracket2_score2;
    private javax.swing.JTextField txt_Tournaments_bracket2_score3;
    private javax.swing.JTextField txt_Tournaments_bracket2_score4;
    private javax.swing.JTextField txt_Tournaments_bracket2_score5;
    private javax.swing.JTextField txt_Tournaments_bracket2_score6;
    private javax.swing.JTextField txt_Tournaments_bracket2_score7;
    private javax.swing.JTextField txt_Tournaments_bracket2_score8;
    private javax.swing.JTextField txt_Tournaments_bracket3_score1;
    private javax.swing.JTextField txt_Tournaments_bracket3_score2;
    private javax.swing.JTextField txt_Tournaments_bracket3_score3;
    private javax.swing.JTextField txt_Tournaments_bracket3_score4;
    private javax.swing.JTextField txt_Tournaments_bracket4_score1;
    private javax.swing.JTextField txt_Tournaments_bracket4_score2;
    private javax.swing.JTextField txt_Tournaments_player1Score;
    private javax.swing.JTextField txt_Tournaments_player1Score1;
    private javax.swing.JTextField txt_Tournaments_player2Score;
    private javax.swing.JTextField txt_Tournaments_player2Score1;
    private javax.swing.JTextField txt_Tournaments_player3Score;
    private javax.swing.JTextField txt_Tournaments_player3Score1;
    private javax.swing.JTextField txt_Tournaments_player4Score;
    private javax.swing.JTextField txt_Tournaments_player4Score1;
    private javax.swing.JTextField txt_Tournaments_player5Score;
    private javax.swing.JTextField txt_Tournaments_player5Score1;
    private javax.swing.JTextField txt_Tournaments_player6Score;
    private javax.swing.JTextField txt_Tournaments_player6Score1;
    private javax.swing.JTextField txt_Tournaments_player7Score;
    private javax.swing.JTextField txt_Tournaments_player7Score1;
    private javax.swing.JTextField txt_Tournaments_player8Score;
    private javax.swing.JTextField txt_Tournaments_player8Score1;
    // End of variables declaration//GEN-END:variables
}
