
import java.awt.Toolkit;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robwo
 */
public class frm_About extends javax.swing.JFrame {

    /**
     * Creates new form frm_About
     */
    public frm_About() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_About = new javax.swing.JPanel();
        lbl_About_authors = new javax.swing.JLabel();
        lbl_About_Crossely = new javax.swing.JLabel();
        lbl_About_Davidson = new javax.swing.JLabel();
        lbl_About_Holden = new javax.swing.JLabel();
        lbl_About_Woods = new javax.swing.JLabel();
        lbl_About_Title = new javax.swing.JLabel();
        btn_About_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl_About.setBackground(new java.awt.Color(0, 41, 60));

        lbl_About_authors.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_authors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_About_authors.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_authors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_authors.setText("Authors:");

        lbl_About_Crossely.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_Crossely.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_About_Crossely.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_Crossely.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_Crossely.setText("Richard Crossely");

        lbl_About_Davidson.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_Davidson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_About_Davidson.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_Davidson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_Davidson.setText("Bruce Davidson");

        lbl_About_Holden.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_Holden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_About_Holden.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_Holden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_Holden.setText("Nickolas Holden");

        lbl_About_Woods.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_Woods.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_About_Woods.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_Woods.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_Woods.setText("Robert Woods");

        lbl_About_Title.setBackground(new java.awt.Color(246, 42, 0));
        lbl_About_Title.setFont(new java.awt.Font("Dialog", 2, 48)); // NOI18N
        lbl_About_Title.setForeground(new java.awt.Color(241, 243, 206));
        lbl_About_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_About_Title.setText("GameTrakker");

        btn_About_Exit.setBackground(new java.awt.Color(246, 42, 0));
        btn_About_Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_About_Exit.setForeground(new java.awt.Color(241, 243, 206));
        btn_About_Exit.setText("Exit");
        btn_About_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_About_ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 243, 206));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Version 1.0");

        javax.swing.GroupLayout pnl_AboutLayout = new javax.swing.GroupLayout(pnl_About);
        pnl_About.setLayout(pnl_AboutLayout);
        pnl_AboutLayout.setHorizontalGroup(
            pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AboutLayout.createSequentialGroup()
                .addGroup(pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_About_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_AboutLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_About_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_About_Woods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_About_Davidson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_About_Holden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_About_Crossely, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(lbl_About_authors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 185, Short.MAX_VALUE))
                    .addGroup(pnl_AboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_AboutLayout.setVerticalGroup(
            pnl_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_About_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_About_authors, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_About_Crossely, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_About_Davidson, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_About_Holden, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_About_Woods, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_About_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method closes this form when the Exit button is clicked.
     * @param evt 
     */
    private void btn_About_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_About_ExitActionPerformed
        // This form is no longer needed so dispose of it
        this.dispose();
    }//GEN-LAST:event_btn_About_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_About_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_About_Crossely;
    private javax.swing.JLabel lbl_About_Davidson;
    private javax.swing.JLabel lbl_About_Holden;
    private javax.swing.JLabel lbl_About_Title;
    private javax.swing.JLabel lbl_About_Woods;
    private javax.swing.JLabel lbl_About_authors;
    private javax.swing.JPanel pnl_About;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("radarlogoIcon.png")));
    }
}
