
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robwo
 */
public class frm_Tournaments_Setup_EnterBowlers extends javax.swing.JFrame {

    /**
     * Creates new form frm_Tournaments
     */
    ArrayList<String> bowlers = new ArrayList();
    int playerId;
    public frm_Tournaments_Setup_EnterBowlers() {
        initComponents();
        setIcon();
        txt_SetupTournament_Name.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_SetupTournament_Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Randombutton = new javax.swing.JButton();
        Area = new javax.swing.JScrollPane();
        bowlerList = new javax.swing.JTextArea();
        menu_Main = new javax.swing.JMenuBar();
        menu_main_File = new javax.swing.JMenu();
        menu_File_Seperator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        menu_UpdateInfo1 = new javax.swing.JMenuItem();
        menu_Delete1 = new javax.swing.JMenuItem();
        menu_Logout = new javax.swing.JMenuItem();
        menu_Menu_File_Exit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menu_Menu_Player_ViewScores = new javax.swing.JMenuItem();
        menu_MainMenu_Player_scorecard = new javax.swing.JMenuItem();
        menu_Menu_Player_EnterScores = new javax.swing.JMenuItem();
        menu_Tournamants = new javax.swing.JMenuItem();
        menu_Leagues = new javax.swing.JMenuItem();
        menu_UpdateInfo = new javax.swing.JMenuItem();
        menu_main_Help = new javax.swing.JMenu();
        menu_About = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_Date = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Bowler");

        txt_SetupTournament_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SetupTournament_NameKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Randombutton.setText("Random List");
        Randombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandombuttonActionPerformed(evt);
            }
        });

        bowlerList.setEditable(false);
        bowlerList.setColumns(20);
        bowlerList.setRows(5);
        Area.setViewportView(bowlerList);

        menu_Main.setBackground(new java.awt.Color(242, 133, 0));
        menu_Main.setForeground(new java.awt.Color(242, 133, 0));

        menu_main_File.setText("File");
        menu_main_File.setToolTipText("File");
        menu_main_File.add(menu_File_Seperator1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settingssmall.png"))); // NOI18N
        jMenu3.setText("Administration");

        menu_UpdateInfo1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menu_UpdateInfo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookmarksmall.png"))); // NOI18N
        menu_UpdateInfo1.setText("Player Infomation");
        menu_UpdateInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_UpdateInfo1ActionPerformed(evt);
            }
        });
        jMenu3.add(menu_UpdateInfo1);

        menu_Delete1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menu_Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash, bin1.png"))); // NOI18N
        menu_Delete1.setText("Delete Account");
        menu_Delete1.setToolTipText("Under Cpntruction");
        menu_Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Delete1ActionPerformed(evt);
            }
        });
        jMenu3.add(menu_Delete1);

        menu_main_File.add(jMenu3);

        menu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning1.png"))); // NOI18N
        menu_Logout.setText("Logout");
        menu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LogoutActionPerformed(evt);
            }
        });
        menu_main_File.add(menu_Logout);

        menu_Menu_File_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_File_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/powerlittle.png"))); // NOI18N
        menu_Menu_File_Exit.setText("Exit");
        menu_Menu_File_Exit.setToolTipText("Exit System");
        menu_Menu_File_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_File_ExitActionPerformed(evt);
            }
        });
        menu_main_File.add(menu_Menu_File_Exit);

        menu_Main.add(menu_main_File);

        jMenu1.setText("Menu");

        menu_Menu_Player_ViewScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_Player_ViewScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats2.png"))); // NOI18N
        menu_Menu_Player_ViewScores.setText("View Scores");
        menu_Menu_Player_ViewScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_Player_ViewScoresActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Menu_Player_ViewScores);

        menu_MainMenu_Player_scorecard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_MainMenu_Player_scorecard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app draw1.png"))); // NOI18N
        menu_MainMenu_Player_scorecard.setText("ScoreCard");
        menu_MainMenu_Player_scorecard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_MainMenu_Player_scorecardActionPerformed(evt);
            }
        });
        jMenu1.add(menu_MainMenu_Player_scorecard);

        menu_Menu_Player_EnterScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_Player_EnterScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foursquare1.png"))); // NOI18N
        menu_Menu_Player_EnterScores.setText("Enter Scores");
        menu_Menu_Player_EnterScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_Player_EnterScoresActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Menu_Player_EnterScores);

        menu_Tournamants.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menu_Tournamants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye in a sky1.png"))); // NOI18N
        menu_Tournamants.setText("Tournaments");
        menu_Tournamants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_TournamantsActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Tournamants);

        menu_Leagues.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menu_Leagues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/browser1.png"))); // NOI18N
        menu_Leagues.setText("Leagues");
        menu_Leagues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LeaguesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Leagues);

        menu_UpdateInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menu_UpdateInfo.setText("Player Infomation");
        menu_UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_UpdateInfoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_UpdateInfo);

        menu_Main.add(jMenu1);

        menu_main_Help.setText("Help");

        menu_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menu_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radarlogoIcon.png"))); // NOI18N
        menu_About.setText("About");
        menu_About.setToolTipText("About");
        menu_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AboutActionPerformed(evt);
            }
        });
        menu_main_Help.add(menu_About);

        menu_Main.add(menu_main_Help);
        menu_Main.add(jMenu2);

        menu_Date.setText("Date");
        menu_Main.add(menu_Date);

        setJMenuBar(menu_Main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SetupTournament_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Randombutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SetupTournament_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Randombutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int counter = 0;
        if ( ! txt_SetupTournament_Name.getText().equals("")){
                 // Add the player name to the bowlers array
            bowlers.add(txt_SetupTournament_Name.getText());
            txt_SetupTournament_Name.setText("");


            // Clear the player list to prevent the players in the array from being displayed multiple times
            bowlerList.setText("");
            //Collections.shuffle(bowlers);

            // Add each name from bowlers array to the player list
            for (String str : bowlers){
                bowlerList.append(str + "\n");
            }
            txt_SetupTournament_Name.requestFocus();

    //        
    //        

    //        for(String s : bowlers){
    //           JLabel label = new JLabel(s);
    //           label.setVisible(true);
    //           labels.add(label);
    //           this.add(label);
    //        }




    //        System.out.println(bowlers);
            
        }else{
            JOptionPane.showMessageDialog(null, "Cannot be Blank");
            txt_SetupTournament_Name.requestFocus();
            
           
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RandombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandombuttonActionPerformed
        // TODO add your handling code here:
        Collections.shuffle(bowlers);
         // Clear the player list to prevent the players in the array from being displayed multiple times
        bowlerList.setText("");
        // Add each name from bowlers array to the player list
        for (String str : bowlers){
            bowlerList.append(str + "\n");
        }
        txt_SetupTournament_Name.requestFocus();
        
//        String player1 = bowlers[0];v
        
    }//GEN-LAST:event_RandombuttonActionPerformed

    private void menu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LogoutActionPerformed
        new frm_LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_LogoutActionPerformed

    private void menu_Menu_File_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_File_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_Menu_File_ExitActionPerformed

    private void menu_Menu_Player_ViewScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_Player_ViewScoresActionPerformed
        int playerId = 0;
        new frm_DisplayScores(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_Menu_Player_ViewScoresActionPerformed

    private void menu_MainMenu_Player_scorecardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_MainMenu_Player_scorecardActionPerformed
        int playerId = 0;
        new frm_BowlingScoreCard(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_MainMenu_Player_scorecardActionPerformed

    private void menu_Menu_Player_EnterScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_Player_EnterScoresActionPerformed
        new frm_EnterBowlingScores(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_Menu_Player_EnterScoresActionPerformed

    private void menu_TournamantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_TournamantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_TournamantsActionPerformed

    private void menu_LeaguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LeaguesActionPerformed
        new frm_Leagues(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_LeaguesActionPerformed

    private void menu_UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_UpdateInfoActionPerformed
        new frm_PlayerInfo(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_UpdateInfoActionPerformed

    private void menu_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AboutActionPerformed
        new frm_About().setVisible(true);
    }//GEN-LAST:event_menu_AboutActionPerformed

    private void txt_SetupTournament_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SetupTournament_NameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                int counter = 0;
            // Add the player name to the bowlers array
            bowlers.add(txt_SetupTournament_Name.getText());
            txt_SetupTournament_Name.setText("");


            // Clear the player list to prevent the players in the array from being displayed multiple times
            bowlerList.setText("");
            //Collections.shuffle(bowlers);

            // Add each name from bowlers array to the player list
            for (String str : bowlers){
                bowlerList.append(str + "\n");
            }
            txt_SetupTournament_Name.requestFocus();
            
            
            
        }
    }//GEN-LAST:event_txt_SetupTournament_NameKeyPressed

    private void menu_UpdateInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_UpdateInfo1ActionPerformed
        new frm_PlayerInfo(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_UpdateInfo1ActionPerformed

    private void menu_Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Delete1ActionPerformed
        int ask = JOptionPane.showConfirmDialog(null, "Do you want to delete your account?");
        // Ask again to make sure the user really wants to delete their account
        if (ask == JOptionPane.YES_OPTION) {
            int delete = JOptionPane.showConfirmDialog(null, "This will permanently"
                + " delete your account and information!\nAre you sure you"
                + " want to delete your account?");
            // Delete account if user answers "yes"
            if (delete == JOptionPane.YES_OPTION) {
                try {
                    // Database connection
                    DBConnect con = new DBConnect();
                    // Delete user's averages
                    int a = con.getStatement().executeUpdate("DELETE FROM BowlerAverages"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's games
                    int b = con.getStatement().executeUpdate("DELETE FROM Games"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's info
                    int c = con.getStatement().executeUpdate("DELETE FROM LoginInfo"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's login info
                    int d = con.getStatement().executeUpdate("DELETE FROM PlayerInfo"
                        + " WHERE PlayerId = '" + playerId + "'");

                    /* Tell user their account has been successfully deleted
                    and return them to the login page */
                    if (a == 1 && c == 1 && d == 1) {
                        new frm_LoginPage().setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Your account has been"
                            + " deleted.");

                    }
                } catch (Exception ex) {
                    System.out.println("ERROR: " + ex);
                }
            }
        }
    }//GEN-LAST:event_menu_Delete1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Tournaments_Setup_EnterBowlers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Tournaments_Setup_EnterBowlers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Tournaments_Setup_EnterBowlers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Tournaments_Setup_EnterBowlers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Tournaments_Setup_EnterBowlers().setVisible(true);
            }
        });
        
    
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("radarlogoIcon.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Area;
    private javax.swing.JButton Randombutton;
    private javax.swing.JTextArea bowlerList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem menu_About;
    private javax.swing.JMenu menu_Date;
    private javax.swing.JMenuItem menu_Delete1;
    private javax.swing.JPopupMenu.Separator menu_File_Seperator1;
    private javax.swing.JMenuItem menu_Leagues;
    private javax.swing.JMenuItem menu_Logout;
    private javax.swing.JMenuBar menu_Main;
    private javax.swing.JMenuItem menu_MainMenu_Player_scorecard;
    private javax.swing.JMenuItem menu_Menu_File_Exit;
    private javax.swing.JMenuItem menu_Menu_Player_EnterScores;
    private javax.swing.JMenuItem menu_Menu_Player_ViewScores;
    private javax.swing.JMenuItem menu_Tournamants;
    private javax.swing.JMenuItem menu_UpdateInfo;
    private javax.swing.JMenuItem menu_UpdateInfo1;
    private javax.swing.JMenu menu_main_File;
    private javax.swing.JMenu menu_main_Help;
    private javax.swing.JTextField txt_SetupTournament_Name;
    // End of variables declaration//GEN-END:variables
}



