
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rob
 */
public class frm_PlayerInfo extends javax.swing.JFrame {
    String[] stateList = {"AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","GU","HI","IA","ID", "IL","IN","KS","KY","LA","MA","MD","ME","MH","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY", "OH","OK","OR","PA","PR","PW","RI","SC","SD","TN","TX","UT","VA","VI","VT","WA","WI","WV","WY"};

    private static int playerId;
    private String email = "";
    private String phone = "";
    private String address = "";
    private String city = "";
    private String state = "AK";
    private int zip = 0;
    /**
     * Creates new form frm_PlayerInfo
     */
    public frm_PlayerInfo(int playerId) {
        initComponents();
        this.setTitle("Player Information");
        setIcon();
        this.playerId = playerId;
        cmb_States.removeAllItems();
        cmb_States.setModel(new javax.swing.DefaultComboBoxModel(stateList));
    }

    frm_PlayerInfo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_Email = new javax.swing.JTextField();
        txt_PhoneNumber = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        txt_City = new javax.swing.JTextField();
        txt_ZipCode = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        lbl_Address1 = new javax.swing.JLabel();
        lbl_City = new javax.swing.JLabel();
        lbl_State = new javax.swing.JLabel();
        lbl_ZipCode = new javax.swing.JLabel();
        btn_PlayerInfo_Clear = new javax.swing.JButton();
        btn_PlayerInfo_Cancel = new javax.swing.JButton();
        cmb_States = new javax.swing.JComboBox<>();
        btn_Update = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_main_File1 = new javax.swing.JMenu();
        menu_File_Seperator2 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        menu_UpdateInfo = new javax.swing.JMenuItem();
        menu_Delete = new javax.swing.JMenuItem();
        menu_Logout = new javax.swing.JMenuItem();
        menu_Menu_File_Exit1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menu_Menu_Player_ViewScores = new javax.swing.JMenuItem();
        menu_MainMenu_Player_scorecard = new javax.swing.JMenuItem();
        menu_Menu_Player_EnterScores = new javax.swing.JMenuItem();
        menu_Tournamants = new javax.swing.JMenuItem();
        menu_Leagues = new javax.swing.JMenuItem();
        menu_main_Help = new javax.swing.JMenu();
        menu_About = new javax.swing.JMenuItem();
        menu_Help_Howto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 41, 60));

        jPanel1.setBackground(new java.awt.Color(0, 41, 60));

        jPanel2.setBackground(new java.awt.Color(0, 41, 60));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0), 2));

        txt_Email.setBackground(new java.awt.Color(241, 243, 206));
        txt_Email.setForeground(new java.awt.Color(0, 41, 60));
        txt_Email.setToolTipText("Enter E-Mail");
        txt_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));

        txt_PhoneNumber.setBackground(new java.awt.Color(241, 243, 206));
        txt_PhoneNumber.setForeground(new java.awt.Color(0, 41, 60));
        txt_PhoneNumber.setToolTipText("Enter Phone Number");
        txt_PhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));

        txt_Address.setBackground(new java.awt.Color(241, 243, 206));
        txt_Address.setToolTipText("Enter Address");
        txt_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));

        txt_City.setBackground(new java.awt.Color(241, 243, 206));
        txt_City.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_City.setForeground(new java.awt.Color(0, 41, 60));
        txt_City.setToolTipText("Enter City");
        txt_City.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));

        txt_ZipCode.setBackground(new java.awt.Color(241, 243, 206));
        txt_ZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ZipCode.setForeground(new java.awt.Color(0, 41, 60));
        txt_ZipCode.setToolTipText("Enter Zip Code");
        txt_ZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 133, 0)));

        lbl_Email.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(241, 243, 206));
        lbl_Email.setText("Email");

        lbl_Phone.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_Phone.setForeground(new java.awt.Color(241, 243, 206));
        lbl_Phone.setText("Phone Number");

        lbl_Address1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_Address1.setForeground(new java.awt.Color(241, 243, 206));
        lbl_Address1.setText("Address");

        lbl_City.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_City.setForeground(new java.awt.Color(241, 243, 206));
        lbl_City.setText("City");

        lbl_State.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_State.setForeground(new java.awt.Color(241, 243, 206));
        lbl_State.setText("State");

        lbl_ZipCode.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbl_ZipCode.setForeground(new java.awt.Color(241, 243, 206));
        lbl_ZipCode.setText("Zip Code");

        btn_PlayerInfo_Clear.setBackground(new java.awt.Color(246, 42, 0));
        btn_PlayerInfo_Clear.setForeground(new java.awt.Color(241, 243, 206));
        btn_PlayerInfo_Clear.setText("Clear");
        btn_PlayerInfo_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlayerInfo_ClearActionPerformed(evt);
            }
        });

        btn_PlayerInfo_Cancel.setBackground(new java.awt.Color(246, 42, 0));
        btn_PlayerInfo_Cancel.setForeground(new java.awt.Color(241, 243, 206));
        btn_PlayerInfo_Cancel.setText("Cancel");
        btn_PlayerInfo_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlayerInfo_CancelActionPerformed(evt);
            }
        });

        cmb_States.setBackground(new java.awt.Color(241, 243, 206));
        cmb_States.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_States.setForeground(new java.awt.Color(0, 41, 60));
        cmb_States.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_States.setToolTipText("States");

        btn_Update.setBackground(new java.awt.Color(246, 42, 0));
        btn_Update.setForeground(new java.awt.Color(241, 243, 206));
        btn_Update.setText("Update Info");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_PlayerInfo_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_PlayerInfo_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btn_Update)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_ZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_State, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_City, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Address1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(lbl_Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_States, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_PhoneNumber)
                                .addComponent(txt_Email)
                                .addComponent(txt_Address)
                                .addComponent(txt_ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Email)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Phone)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_PhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Address1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_City, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_City)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_States, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_State))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ZipCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PlayerInfo_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PlayerInfo_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        menu_main_File1.setText("File");
        menu_main_File1.setToolTipText("File");
        menu_main_File1.add(menu_File_Seperator2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settingssmall.png"))); // NOI18N
        jMenu3.setText("Administration");

        menu_UpdateInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menu_UpdateInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookmarksmall.png"))); // NOI18N
        menu_UpdateInfo.setText("Player Infomation");
        menu_UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_UpdateInfoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_UpdateInfo);

        menu_Delete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menu_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash, bin1.png"))); // NOI18N
        menu_Delete.setText("Delete Account");
        menu_Delete.setToolTipText("Under Cpntruction");
        menu_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_DeleteActionPerformed(evt);
            }
        });
        jMenu3.add(menu_Delete);

        menu_main_File1.add(jMenu3);

        menu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning1.png"))); // NOI18N
        menu_Logout.setText("Logout");
        menu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LogoutActionPerformed(evt);
            }
        });
        menu_main_File1.add(menu_Logout);

        menu_Menu_File_Exit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_File_Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash, bin1.png"))); // NOI18N
        menu_Menu_File_Exit1.setText("Exit");
        menu_Menu_File_Exit1.setToolTipText("Exit System");
        menu_Menu_File_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_File_Exit1ActionPerformed(evt);
            }
        });
        menu_main_File1.add(menu_Menu_File_Exit1);

        jMenuBar1.add(menu_main_File1);

        jMenu1.setText("Menu");

        menu_Menu_Player_ViewScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_Player_ViewScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats2.png"))); // NOI18N
        menu_Menu_Player_ViewScores.setText("View Scores");
        menu_Menu_Player_ViewScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_Player_ViewScoresActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Menu_Player_ViewScores);

        menu_MainMenu_Player_scorecard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_MainMenu_Player_scorecard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app draw1.png"))); // NOI18N
        menu_MainMenu_Player_scorecard.setText("ScoreCard");
        menu_MainMenu_Player_scorecard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_MainMenu_Player_scorecardActionPerformed(evt);
            }
        });
        jMenu1.add(menu_MainMenu_Player_scorecard);

        menu_Menu_Player_EnterScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menu_Menu_Player_EnterScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foursquare1.png"))); // NOI18N
        menu_Menu_Player_EnterScores.setText("Enter Scores");
        menu_Menu_Player_EnterScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Menu_Player_EnterScoresActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Menu_Player_EnterScores);

        menu_Tournamants.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menu_Tournamants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye in a sky1.png"))); // NOI18N
        menu_Tournamants.setText("Tournaments");
        menu_Tournamants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_TournamantsActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Tournamants);

        menu_Leagues.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menu_Leagues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/browser1.png"))); // NOI18N
        menu_Leagues.setText("Leagues");
        menu_Leagues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_LeaguesActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Leagues);

        jMenuBar1.add(jMenu1);

        menu_main_Help.setText("Help");

        menu_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menu_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radarlogoIcon.png"))); // NOI18N
        menu_About.setText("About");
        menu_About.setToolTipText("About");
        menu_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AboutActionPerformed(evt);
            }
        });
        menu_main_Help.add(menu_About);

        menu_Help_Howto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/messages2small.png"))); // NOI18N
        menu_Help_Howto.setText("Help");
        menu_Help_Howto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Help_HowtoActionPerformed(evt);
            }
        });
        menu_main_Help.add(menu_Help_Howto);

        jMenuBar1.add(menu_main_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method clears the form when the Clear button is clicked.
     * @param evt 
     */
    private void btn_PlayerInfo_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlayerInfo_ClearActionPerformed
        txt_Email.setText("");
        txt_PhoneNumber.setText("");
        txt_Address.setText("");
        txt_City.setText("");
        txt_ZipCode.setText(""); 
        cmb_States.setSelectedIndex(0);
    }//GEN-LAST:event_btn_PlayerInfo_ClearActionPerformed

    /**
     * This method cancels the player registration and returns to the login page
     * when the Cancel button is clicked.
     * @param evt 
     */
    private void btn_PlayerInfo_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlayerInfo_CancelActionPerformed
        new frm_Main(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_PlayerInfo_CancelActionPerformed

    private void menu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LogoutActionPerformed
        new frm_LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_LogoutActionPerformed

    private void menu_Menu_File_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_File_Exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_Menu_File_Exit1ActionPerformed

    private void menu_Menu_Player_ViewScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_Player_ViewScoresActionPerformed
        new frm_DisplayScores(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_Menu_Player_ViewScoresActionPerformed

    private void menu_MainMenu_Player_scorecardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_MainMenu_Player_scorecardActionPerformed
        new frm_BowlingScoreCard(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_MainMenu_Player_scorecardActionPerformed

    private void menu_Menu_Player_EnterScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Menu_Player_EnterScoresActionPerformed
        new frm_EnterBowlingScores(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_Menu_Player_EnterScoresActionPerformed

    private void menu_TournamantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_TournamantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_TournamantsActionPerformed

    private void menu_LeaguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_LeaguesActionPerformed
        new frm_Leagues(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_LeaguesActionPerformed

    private void menu_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AboutActionPerformed
        new frm_About().setVisible(true);
    }//GEN-LAST:event_menu_AboutActionPerformed

    private void menu_Help_HowtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Help_HowtoActionPerformed
        // TODO add your handling code here:
        try{
            //            String URL = "Howto/GameTrakker_HowTo.html";
            //            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

            Desktop.getDesktop().open(new File("Howto\\GameTrakker_HowTo.html"));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_menu_Help_HowtoActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // Initialize variables
        email = txt_Email.getText();
        phone = txt_PhoneNumber.getText();
        address = txt_Address.getText();
        city = txt_City.getText();
        state = cmb_States.getItemAt(cmb_States.getSelectedIndex());
        String zipCode = txt_ZipCode.getText();
        // Check if zip code is 5 characters long
        if(zipCode.length() == 5 || zipCode.equals("")){
            // Check if zip code is a valid number
            try{
                // If no zip code has been entered then zip equals zero
                if(zipCode.equals("")){
                    zip = 0;
                }else{
                    zip = Integer.parseInt(zipCode);
                }
                // Check if zip code is a positive number
                if(zip < 0){
                    JOptionPane.showMessageDialog(null, "Invalid Zip Code");
                    txt_ZipCode.setText("");
                }else{
                    // Connect to database and update player info
                    try{
                        // Connect to the database
                        DBConnect con = new DBConnect();
                        // Update player info
                        int a = con.getStatement().executeUpdate("UPDATE " +
                            "PlayerInfo SET Email='" + email + "', Address" +
                            "='" + address + "', City='" + city + "', State='" + state +
                            "', ZIPCode='" + zip + "', Phone='" + phone +
                            "' WHERE PlayerId = '" + playerId + "'");
                        // If update statement was successful then return to main
                        if(a == 1){
                            JOptionPane.showMessageDialog(null, "Successful");

                            new frm_Main(playerId).setVisible(true);
                            this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Failed");
                        }
                    }catch(Exception ex){
                        System.out.println("ERROR: " + ex);
                    }
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Invalid Zip Code.");
                txt_ZipCode.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Invalid Zip Code.");
            txt_ZipCode.setText("");
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void menu_UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_UpdateInfoActionPerformed
        new frm_PlayerInfo(playerId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_UpdateInfoActionPerformed

    private void menu_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_DeleteActionPerformed
        int ask = JOptionPane.showConfirmDialog(null, "Do you want to delete your account?");
        // Ask again to make sure the user really wants to delete their account
        if (ask == JOptionPane.YES_OPTION) {
            int delete = JOptionPane.showConfirmDialog(null, "This will permanently"
                + " delete your account and information!\nAre you sure you"
                + " want to delete your account?");
            // Delete account if user answers "yes"
            if (delete == JOptionPane.YES_OPTION) {
                try {
                    // Database connection
                    DBConnect con = new DBConnect();
                    // Delete user's averages
                    int a = con.getStatement().executeUpdate("DELETE FROM BowlerAverages"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's games
                    int b = con.getStatement().executeUpdate("DELETE FROM Games"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's info
                    int c = con.getStatement().executeUpdate("DELETE FROM LoginInfo"
                        + " WHERE PlayerId = '" + playerId + "'");
                    // Delete user's login info
                    int d = con.getStatement().executeUpdate("DELETE FROM PlayerInfo"
                        + " WHERE PlayerId = '" + playerId + "'");

                    /* Tell user their account has been successfully deleted
                    and return them to the login page */
                    if (a == 1 && c == 1) {
                        new frm_LoginPage().setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Your account has been"
                            + " deleted.");

                    }
                } catch (Exception ex) {
                    System.out.println("ERROR: " + ex);
                }
            }
        }
    }//GEN-LAST:event_menu_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_PlayerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_PlayerInfo(playerId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PlayerInfo_Cancel;
    private javax.swing.JButton btn_PlayerInfo_Clear;
    private javax.swing.JButton btn_Update;
    private javax.swing.JComboBox<String> cmb_States;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Address1;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_State;
    private javax.swing.JLabel lbl_ZipCode;
    private javax.swing.JMenuItem menu_About;
    private javax.swing.JMenuItem menu_Delete;
    private javax.swing.JPopupMenu.Separator menu_File_Seperator2;
    private javax.swing.JMenuItem menu_Help_Howto;
    private javax.swing.JMenuItem menu_Leagues;
    private javax.swing.JMenuItem menu_Logout;
    private javax.swing.JMenuItem menu_MainMenu_Player_scorecard;
    private javax.swing.JMenuItem menu_Menu_File_Exit1;
    private javax.swing.JMenuItem menu_Menu_Player_EnterScores;
    private javax.swing.JMenuItem menu_Menu_Player_ViewScores;
    private javax.swing.JMenuItem menu_Tournamants;
    private javax.swing.JMenuItem menu_UpdateInfo;
    private javax.swing.JMenu menu_main_File1;
    private javax.swing.JMenu menu_main_Help;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_City;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_PhoneNumber;
    private javax.swing.JTextField txt_ZipCode;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("radarlogoIcon.png")));
    }
}
